Repository edmcouncil/idmp, pull requests merged in 2022-12, with the labels that each got.

#247 IDMP-366: Add RIM related IDMP concept: Packaged Medicinal Product
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
  EXT/Examples/TerlipressinExample.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  ISO/catalog-v001.xml
Labels: enhancement

#250 IDMP-GitHub-249 - Wrong versionIRI in ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
  ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
Labels: bug

#257 IDMP-357 - Add EMA SPOR SMS 'substance domain' to the Substances ontology
  AboutIDMPDev-ReferenceIndividuals.rdf
  AboutIDMPDev.rdf
  AboutIDMPProd-ReferenceIndividuals.rdf
  AboutIDMPProd.rdf
  CMNS/EuropeanJurisdiction/UKGovernmentEntitiesAndJurisdictions.rdf
  ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
  ISO/EuropeanJurisdiction/catalog-v001.xml
  ISO/MetadataISO.rdf
  ISO/catalog-v001.xml
  catalog-v001.xml
Labels: enhancement

#262 IDMP-367 - Include SKUs in IDMP-O
  CMNS/ProductsAndServices.rdf
Labels: enhancement

#267 Performance driven hygiene tests
  etc/testing/hygiene_parameterized/testHygiene_performance_allValuesFrom_equivalent.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_cgi_with_equivalent.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_cgi_with_subclassof.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_complement_equivalent.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_high_max_restriction.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_high_min_restriction.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_left_subclass_and_equivalent.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_multiple_different_individuals.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_multiple_disjuncts.sparql
  etc/testing/hygiene_parameterized/testHygiene_performance_thing_equivalent.sparql
Labels: hygiene

#272 IDMP-390 - Add annotations to suggest changes to definitions that are needed in the IDMP standard
  ISO/ISO11238-Substances.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  META/ISOConformanceAnnotations.rdf
Labels: enhancement, compliance

#270 IDMP-348 - ISO conformance report as a hygiene test
  etc/testing/hygiene_parameterized/testHygiene_reporting_iso_conformance.sparql
Labels: hygiene

#275 Update catalog-v001.xml to fix an obsolete Locations.rdf resolution
  EXT/Examples/catalog-v001.xml
Labels: metadata

#274 IDMP-391 - The relationship between structure and structural representation should be better defined
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/TerlipressinExample.rdf
  ISO/ISO11238-Substances.rdf
Labels: bug, compliance
