Repository edmcouncil/idmp, pull requests merged in 2023-10, with the labels that each got.

#490 Some spelling typos fixed
  ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
  ISO/ISO11238-RegistrationAuthorities.rdf
  ISO/ISO11238-Substances.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  ISO/ISO21090-HarmonizedDatatypes.rdf
  ISO/NorthAmericanJurisdiction/NorthAmericanRegistrationAuthorities.rdf
Labels: bug, spelling

#486 IDMP-632 - Batch should be a subclass of Constituent rather than Product
  ISO/ISO11615-MedicinalProducts.rdf
Labels: invalid

#493 IDMP-661 - Revise the Amlodipine example to match the current patterns for strength and reference strength
  EXT/Examples/AmlodipineExample.rdf
Labels: invalid

#495 IDMP-662 - Revise the Terlipressin example to address hygiene issues
  EXT/Examples/TerlipressinExample.rdf
Labels: enhancement

#491 AboutIDMPDev-ReferenceIndividuals.rdf alignment with AboutIDMPDev.rdf
  AboutIDMPDev.rdf
Labels: bug

#499 More possible typos in annotations fixed
  EXT/Examples/AmlodipineExample.rdf
  ISO/EuropeanJurisdiction/EuropeanRegulatoryAgencies.rdf
  ISO/ISO11238-RegistrationAuthorities.rdf
  ISO/ISO11238-Substances.rdf
  ISO/ISO21090-HarmonizedDatatypes.rdf
  ISO/MedicalDictionaryForRegulatoryActivities.rdf
  etc/CQ/Example/uc1_cq1.sparql
  etc/CQ/Example/uc1_cq2.sparql
  etc/CQ/Example/uc1_cq3-1.sparql
  etc/CQ/Example/uc1_cq3.sparql
  etc/CQ/Example/uc1_cq4.sparql
  etc/CQ/Example/uc1_cq6.sparql
  etc/CQ/Example/uc1_cq9.sparql
  etc/CQ/Example/uc2_cq1-2.sparql
  etc/CQ/Example/uc2_cq1.sparql
  etc/CQ/Example/uc2_cq1a.sparql
  etc/CQ/Example/uc2_cq1b.sparql
  etc/CQ/Example/uc2_cq1d.sparql
  etc/CQ/Example/uc2_cq2-1.sparql
Labels: bug, spelling

#500 Spellcheck automation as a GitHub action
  .github/workflows/spellcheck_run.yml
  etc/testing/spelling/domain_specific_spellings.json
  etc/testing/spelling/onto_spellchecker.py
  etc/testing/spelling/requirements.txt
Labels: hygiene, spelling

#503 IDMP-665 - Update the Qlaira example to use the proper IRIs for the SPOR details
  EXT/Examples/QlairaExample.rdf
  etc/CQ/Example/uc1_cq3.sparql
  etc/testing/spelling/domain_specific_spellings.json
  etc/testing/spelling/onto_spellchecker.py
  etc/unit_tests/cq_expected_results/IDMP/uc1_cq3_amlodipine_expected_results.json
  etc/unit_tests/cq_expected_results/IDMP/uc1_cq3_terlipressin_expected_results.json
Labels: invalid

#504 IDMP-594 - Complete the definition of protein substances
  ISO/ISO11238-Substances.rdf
  etc/testing/spelling/domain_specific_spellings.json
Labels: enhancement

#509 IDMP-673 - Complete the minimal set of required fields from Annex L for Polymers
  ISO/ISO11238-Substances.rdf
  etc/testing/spelling/domain_specific_spellings.json
Labels: enhancement, UC1

#516 GitHub-511 - dmp-sub:SubstanceNameClassifier-CommonName has incomplete definition
  ISO/ISO11238-Substances.rdf
Labels: invalid, reference data

#514 GitHub-505 - Non-classifying, but just denoting, classifiers
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/QlairaExample.rdf
  EXT/Examples/QlairaExample.ttl
Labels: invalid, examples

#518 IDMP-674 - Exclude shelf life type and special precautions for storage from the SPOR ontology in advance of regeneration of the SPOR lists and vocabulary elements
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/TerlipressinExample.rdf
  ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
  etc/CQ/Example/uc3_cq3.sparql
Labels: reference data
