Repository edmcouncil/idmp, pull requests merged in 2023-04, with the labels that each got.

#329 IDMP-479 - Further clean-up is needed to address remaining issues with the Qlaira example
  EXT/Examples/QlairaExample.rdf
  EXT/Examples/catalog-v001.xml
Labels: bug, UC2, reference data

#330 New cqs added as unit tests
  etc/CQ/Example/uc1_cq8.sparql
  etc/CQ/Example/uc2_cq1b.sparql
  etc/CQ/Example/uc2_cq1c.sparql
  etc/CQ/Example/uc2_cq2-2.sparql
  etc/unit_tests/configs/unit_tests_config.yaml
  etc/unit_tests/cq_expected_results/uc1_cq3-1_expected_results.json
  etc/unit_tests/cq_expected_results/uc1_cq3-1a_expected_results.json
  etc/unit_tests/cq_expected_results/uc1_cq3-1b_expected_results.json
  etc/unit_tests/cq_expected_results/uc1_cq3a_expected_results.json
  etc/unit_tests/cq_expected_results/uc1_cq3b_expected_results.json
  etc/unit_tests/cq_expected_results/uc1_cq4-1_expected_results.json
  etc/unit_tests/cq_expected_results/uc1_cq8_expected_results.json
  etc/unit_tests/cq_expected_results/uc2_cq1-2_expected_results.json
  etc/unit_tests/cq_expected_results/uc2_cq1_expected_results.json
  etc/unit_tests/cq_expected_results/uc2_cq1a_expected_results.json
  etc/unit_tests/cq_expected_results/uc2_cq1b_expected_results.json
  etc/unit_tests/cq_expected_results/uc2_cq1d_expected_results.json
  etc/unit_tests/cq_expected_results/uc2_cq2-1_expected_results.json
Labels: competency question, UC1, UC2, unit test

#339 IDMP-512 - Need the concept of an ordered collection to define polymers
  CMNS/AboutCommons-ReferenceIndividuals.rdf
  CMNS/AboutCommons.rdf
  CMNS/MetadataCMNS.rdf
  CMNS/StructuredCollections.rdf
  CMNS/catalog-v001.xml
Labels: enhancement

#336 IDMP-483 - Complete the set of optional fields from Annex L: for Substance and Chemical Substance (excluding the reference information from Figure 16)
  ISO/ISO11238-Substances.rdf
Labels: enhancement, UC1, UC2

#343 IDMP-525 - Release the ISO 11615 Medicinal Products Ontology
  AboutIDMPProd-ReferenceIndividuals.rdf
  AboutIDMPProd.rdf
  ISO/ISO11615-MedicinalProducts.rdf
Labels: enhancement
