Repository edmcouncil/idmp, pull requests merged in 2023-09, with the labels that each got.

#448 IDMP-533a - Provide alignment/mapping for ISO "codedConcept" to the target IDMP-O Pattern for Reference Code Lists
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/TerlipressinExample.rdf
  ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
  ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
  ISO/ISO11238-Substances.rdf
Labels: enhancement, reference data

#464 Fix to some typos in unit tests
  etc/CQ/Example/uc1_cq3-1.sparql
  etc/unit_tests/cq_expected_results/IDMP/uc1_cq3-1_amlodipine_expected_results.json
  etc/unit_tests/cq_expected_results/IDMP/uc1_cq3-1_terlipressin_expected_results.json
Labels: unit test

#466 IDMP-GitHub-465 - idmp-spor:hasSPORTermDescription is language dependent
  ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
Labels: enhancement

#441 IDMP-635 - Augment the substance ontology with coverage for structurally diverse substances
  ISO/ISO11238-Substances.rdf
Labels: enhancement, UC1

#474 IDMP-654 - Remove deprecated elements prior to 1.0 release
  AboutIDMPDev-ReferenceIndividuals.rdf
  AboutIDMPDev.rdf
  AboutIDMPProd-ReferenceIndividuals.rdf
  AboutIDMPProd.rdf
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/TerlipressinExample.rdf
  ISO/ISO11238-RegistrationAuthorities.rdf
  ISO/ISO11238-Substances-DeprecatedElements.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  ISO/MetadataISO.rdf
  ISO/catalog-v001.xml
  META/ChangeManagement.rdf
  catalog-v001.xml
Labels: enhancement

#476 IDMP-655 - Revise the Commons ontologies and related changes for Commons 1.1
  AboutIDMPDev-ReferenceIndividuals.rdf
  AboutIDMPDev.rdf
  AboutIDMPProd-ReferenceIndividuals.rdf
  AboutIDMPProd.rdf
  CMNS/AboutCommons-ReferenceIndividuals.rdf
  CMNS/AboutCommons.rdf
  CMNS/DatesAndTimes.rdf
  CMNS/Documents.rdf
  CMNS/EuropeanJurisdiction/EUGovernmentEntitiesAndJurisdictions.rdf
  CMNS/GovernmentEntities.rdf
  CMNS/MetadataCMNS.rdf
  CMNS/Organizations.rdf
  CMNS/PartiesAndSituations.rdf
  CMNS/ProductsAndServices.rdf
  CMNS/QuantitiesAndUnits.rdf
  CMNS/RegulatoryAgencies.rdf
  CMNS/RolesAndCompositions.rdf
  CMNS/StatisticalMeasures.rdf
  CMNS/catalog-v001.xml
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
  EXT/Examples/QlairaExample.rdf
  EXT/Examples/QlairaExample.ttl
  EXT/Examples/TerlipressinExample.rdf
  ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
  ISO/EuropeanJurisdiction/EuropeanRegulatoryAgencies.rdf
  ISO/ISO11238-RegistrationAuthorities.rdf
  ISO/ISO11238-Substances.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  ISO/ISO21090-HarmonizedDatatypes.rdf
  ISO/MedicalDictionaryForRegulatoryActivities.rdf
  ISO/NorthAmericanJurisdiction/NorthAmericanRegistrationAuthorities.rdf
  ISO/NorthAmericanJurisdiction/NorthAmericanRegulatoryAgencies.rdf
  ISO/catalog-v001.xml
  MetadataIDMP.rdf
  catalog-v001.xml
  etc/CQ/Example/uc1_cq1.sparql
  etc/CQ/Example/uc1_cq2.sparql
  etc/CQ/Example/uc1_cq3-1.sparql
  etc/CQ/Example/uc1_cq3.sparql
  etc/CQ/Example/uc1_cq6.sparql
  etc/CQ/Example/uc1_cq7.sparql
  etc/CQ/Example/uc1_cq8.sparql
  etc/CQ/Example/uc2_cq1-2.sparql
  etc/CQ/Example/uc2_cq1.sparql
  etc/CQ/Example/uc2_cq1a.sparql
  etc/CQ/Example/uc2_cq1b.sparql
  etc/CQ/Example/uc2_cq2-1.sparql
  etc/CQ/Example/uc3_cq1-1.sparql
  etc/CQ/Example/uc3_cq2.sparql
  etc/CQ/Example/uc3_cq3.sparql
  etc/transformation/GSRS/gsrs-public-data-relationships.rqg
Labels: enhancement, CMNS

#483 hasShelfLifeTimePeriod should expect a cmns-dt:Duration instead of cmns-dt:DatePeriod for medicinal products
  ISO/ISO11615-MedicinalProducts.rdf
Labels: bug

#484 Update IRIs in transformation scripts
  etc/transformation/GSRS/gsrs-public-data-identifiers.rqg
  etc/unit_tests/configs/gsrs_tests_config.yaml
Labels: unit test, GSRS v3.0.3

#488 IDMP-592 - Complete the preliminary modeling work required for Nucleic Acid, covering all detail provided in ISO 11238
  ISO/ISO11238-Substances.rdf
Labels: enhancement
