Repository edmcouncil/idmp, pull requests merged in 2023-01, with the labels that each got.

#277 IDMP-387 - Complete the set of terms required to answer UC-2, CQ-1
  ISO/ISO11615-MedicinalProducts.rdf
Labels: enhancement

#280 single substance has max 1 molecular structure is wrong
  ISO/ISO11238-Substances.rdf
Labels: bug

#285 IDMP-GitHub-284 - Notes on certain classes for structure, molecular structure, and stereochemistry are needed
  ISO/ISO11238-Substances.rdf
Labels: documentation, enhancement

#290 IDMP-398 - Add concept for Marketing Status (SPOR RMS)
  ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
Labels: enhancement, reference data

#297 Competency questions split to one query per file
  etc/CQ/Example/cq3-1a.sparql
  etc/CQ/Example/cq3-1b.sparql
  etc/CQ/Example/cq3a.sparql
  etc/CQ/Example/cq3b.sparql
Labels: competency question

#287 Add more cleanup instructions for SPOR OMS transformation
  etc/transformation/SPOR/organisations/README.md
Labels: documentation
