Repository edmcouncil/idmp, pull requests merged in 2023-07, with the labels that each got.

#388 Update of IDMP viewer config
  etc/onto-viewer-web-app/config/label_config.yaml
  etc/onto-viewer-web-app/config/search_config.yaml
Labels: onto-viewer config

#401 IDMP-602 - Loosen the restriction on ingredient to say that it -may- be manifested in a manufactured item
  ISO/ISO11615-MedicinalProducts.rdf
Labels: invalid, UC2

#403 IDMP-601 - Add a disclaimer to example ontologies
  .gitignore
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
  EXT/Examples/QlairaExample.rdf
  EXT/Examples/QlairaExample.ttl
  EXT/Examples/TerlipressinExample.rdf
Labels: enhancement, reference data

#414 IDMP-599 Adding UC2-CQ1 Amlodipine to sparql and unit tests.
  etc/CQ/Example/uc2_cq1.sparql
  etc/unit_tests/configs/idmp_tests_config.yaml
  etc/unit_tests/cq_expected_results/IDMP/uc2_cq1_amlodipine_expected_results.json
Labels: UC2, unit test

#293 IDMP-371 - Add RIM related SPOR Referentials: Shelf Life Type and Special Precautions for Storage
  ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf
  ISO/ISO11615-MedicinalProducts.rdf
Labels: enhancement, reference data

#416 GitHub-278 - hasSimplifiedMolecularInputLineEntrySpecification is misleading and inconsistent
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/TerlipressinExample.rdf
  ISO/ISO11238-Substances-DeprecatedElements.rdf
  ISO/ISO11238-Substances.rdf
  etc/CQ/Example/uc1_cq9.sparql
  etc/transformation/GSRS/gsrs-public-data-substances.rqg
Labels: invalid

#230 IDMP-138 - Extension of Registration Authorities
  AboutIDMPDev-ReferenceIndividuals.rdf
  AboutIDMPDev.rdf
  CMNS/Organizations.rdf
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/TerlipressinExample.rdf
  ISO/EuropeanJurisdiction/EuropeanRegulatoryAgencies.rdf
  ISO/ISO11238-RegistrationAuthorities.rdf
  ISO/MetadataISO.rdf
  ISO/NorthAmericanJurisdiction/NorthAmericanRegistrationAuthorities.rdf
  ISO/NorthAmericanJurisdiction/NorthAmericanRegulatoryAgencies.rdf
  ISO/catalog-v001.xml
  catalog-v001.xml
Labels: enhancement, hygiene

#397 IDMP-597 Revise therapeutic text
  EXT/Examples/AmlodipineExample.rdf
  EXT/Examples/CellCeptExample.rdf
  EXT/Examples/TerlipressinExample.rdf
  ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
  ISO/ISO11238-RegistrationAuthorities.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  etc/CQ/Example/uc3_cq1-1.sparql
  etc/unit_tests/cq_expected_results/IDMP/uc3_cq1-1_expected_results.json
Labels: UC3

#424 IDMP-614 add route of administration
  EXT/Examples/QlairaExample.rdf
  EXT/Examples/QlairaExample.ttl
  ISO/ISO11615-MedicinalProducts.rdf
Labels: enhancement, UC3

#427 owl:sameAs added to ignored properties of test for deprecated properties
  etc/testing/hygiene_parameterized/testHygiene_deprecated.sparql
Labels: hygiene

#426 IDMP-533 - Provide alignment/mapping for ISO "codedConcept" to the target IDMP-O Pattern for Reference Code Lists
  AboutIDMPDev-ReferenceIndividuals.rdf
  AboutIDMPDev.rdf
  AboutIDMPProd-ReferenceIndividuals.rdf
  AboutIDMPProd.rdf
  ISO/ISO11238-Substances.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  ISO/ISO21090-HarmonizedDatatypes.rdf
  MVF/AboutMVF.rdf
  MVF/ISO1087-TerminologyScience.rdf
  MVF/ISO1087-VocabularyForTermsAndDefinitions.rdf
  MVF/MVFtoSKOSMapping.rdf
  MVF/MetadataMVF.rdf
  MVF/MultipleVocabularyFacility.rdf
  MVF/catalog-v001.xml
  MetadataIDMP.rdf
  catalog-v001.xml
Labels: enhancement, UC3

#435 GitHub-434 - cmns-ra:designates is equivalent to cmns-ra:isDesignatedBy
  CMNS/RegistrationAuthorities.rdf
Labels: bug, CMNS
