Repository edmcouncil/idmp, pull requests merged in 2023-11, with the labels that each got.

#520 IDMP-634 - Remove the default code for ingredient and active ingredient
  ISO/ISO11615-MedicinalProducts.rdf
Labels: consistency

#453 IDMP-640 add characteristics for target populations
  ISO/ISO11238-Substances.rdf
  ISO/ISO11240-UnitsOfMeasurement.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  etc/transformation/EDQM/transformation/generic_transformation.rqg
Labels: UC2

#522 IDMP-675 - Complete the minimal set of required fields from Annex L for Mixtures
  ISO/ISO11238-Substances.rdf
Labels: enhancement

#534 Spellcheck ignores reified languages
  etc/testing/spelling/onto_spellchecker.py
Labels: spelling
