Repository edmcouncil/idmp, pull requests merged in 2023-06, with the labels that each got.

#379 IDMP-561 - Augment the IDMP ontologies to cover therapeutic indications
  AboutIDMPDev-ReferenceIndividuals.rdf
  AboutIDMPDev.rdf
  AboutIDMPProd-ReferenceIndividuals.rdf
  AboutIDMPProd.rdf
  CMNS/AboutCommons-ReferenceIndividuals.rdf
  CMNS/AboutCommons.rdf
  CMNS/MetadataCMNS.rdf
  CMNS/QuantitiesAndUnits.rdf
  CMNS/RegistrationAuthorities.rdf
  CMNS/StatisticalMeasures.rdf
  CMNS/catalog-v001.xml
  EXT/Examples/AmlodipineExample.rdf
  ISO/ISO11238-RegistrationAuthorities.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  ISO/ISO11616-PharmaceuticalProducts.rdf
  catalog-v001.xml
Labels: enhancement, competency question, UC3, reference data

#381 IDMP-395 - Check definition for 'marketing authorization holder'
  ISO/ISO11615-MedicinalProducts.rdf
Labels: metadata, UC2

#390 Legal punning in d9ececf commit in master
  ISO/ISO11238-Substances.rdf
Labels: invalid

#392 IDMP-550 - Document the modelling pattern for Marketing Authorization
  ISO/ISO11615-MedicinalProducts.rdf
Labels: enhancement, UC1
