Repository edmcouncil/idmp, pull requests merged in 2024-09, with the labels that each got.

#634 Checks for punning on classes and individuals
  etc/testing/hygiene_parameterized/testHygiene_classes_used_as_individuals_in_owl_punning.sparql
  etc/testing/hygiene_parameterized/testHygiene_classes_used_as_individuals_punning.sparql
  etc/testing/hygiene_parameterized/testHygiene_individuals_used_as_classes_punning.sparql
Labels: hygiene

#638 IDMP-779 - Augment the ISO 11615 ontology to include a property chain from manufacturer to the manufacturing site
  ISO/ISO11238-Substances.rdf
  ISO/ISO11615-MedicinalProducts.rdf
Labels: enhancement

#640 IDMP-776 - Harmonize Strength naming: Change "Concentration" to "Concentration Strength"
  EXT/Examples/TerlipressinExample.rdf
  ISO/ISO11615-MedicinalProducts.rdf
Labels: consistency
