Repository edmcouncil/idmp, pull requests merged in 2024-04, with the labels that each got.

#559 IDMP-726 - Augment / revise the ontology to cover gaps w.r.t. ISO 11615 for UC4
  ISO/ISO11615-MedicinalProducts.rdf
Labels: enhancement

#562 IDMP-GitHub-561 - addressed case issue in subClass axiom
  ISO/ISO11615-MedicinalProducts.rdf
Labels: bug

#566 IDMP-GitHub-564 - Textual values for substance names
  ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
  ISO/ISO11238-RegistrationAuthorities.rdf
  ISO/ISO11238-Substances.rdf
  ISO/NorthAmericanJurisdiction/NorthAmericanRegistrationAuthorities.rdf
Labels: consistency

#568 IDMP-GitHub-567 - Two typos in reference to rdfs:subPropertyOf
  ISO/ISO11615-MedicinalProducts.rdf
Labels: bug

#574 IDMP-GitHub-573 - Correct a wrong prefix for reference source
  ISO/ISO11238-Substances.rdf
Labels: bug

#572 IDMP-GitHub-571 - Simplify the licensing definitions in Commons to facilitate mapping to BFO
  CMNS/ProductsAndServices.rdf
  CMNS/RegulatoryAgencies.rdf
Labels: enhancement

#575 hygiene tests added for prefLabels
  etc/testing/hygiene_parameterized/testHygiene_single_preflabels.sparql
  etc/testing/hygiene_parameterized/testHygiene_unique_preflabels.sparql
Labels: hygiene

#570 IDMP-734 - Add skos:prefLabel to terms that have multilingual labels
  CMNS/Organizations.rdf
  ISO/ISO11238-Substances.rdf
  ISO/ISO11615-MedicinalProducts.rdf
Labels: consistency

#563 IDMP-720 - Few SHACL examples added for discussion
  etc/shacl/chemicalsubstance_shacl_auto.ttl
  etc/shacl/chemicalsubstance_shacl_human.shacl
  etc/shacl/proteinsubstance_shacl_auto.ttl
  etc/shacl/proteinsubstance_shacl_human.shacl
  etc/shacl/substance_shacl_auto.ttl
  etc/shacl/substance_shacl_human.shacl
Labels: Shacl

#592 GitHub-589 - Improper references to IDMP resources
  ISO/ISO11238-Substances.rdf
  ISO/ISO11615-MedicinalProducts.rdf
  ISO/ISO21090-HarmonizedDatatypes.rdf
Labels: bug, consistency

#585 IDMP-GitHub-584 - Loosen constraints on MVF Element to allow for mapping MEDdra terms to those in EMA SPOR and other vocabularies
  MVF/MultipleVocabularyFacility.rdf
Labels: consistency

#591 GitHub-590 - Missing disjointness axiom on starting material role
  ISO/ISO11238-Substances.rdf
Labels: consistency
